import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Fragment } from "react";
import { Disclosure, Menu, Transition } from "@headlessui/react";
import { Bars3Icon, BellIcon, XMarkIcon } from "@heroicons/react/24/outline";
import { useSelector, useDispatch } from "react-redux";
import { NavLink, Link } from "react-router-dom";
import { logoutUser } from "../features/auth/authSlice";
const navigation = [
    { name: "Dashboard", href: "/MyDashBoard", current: true },
    { name: "Team", href: "#", current: false },
    { name: "Projects", href: "#", current: false },
    { name: "Calendar", href: "#", current: false },
];
function classNames(...classes) {
    return classes.filter(Boolean).join(" ");
}
export default function Navbar() {
    const { userInfo } = useSelector((state) => state.auth);
    const dispatch = useDispatch();
    return (_jsx(Disclosure, { as: "nav", className: "bg-gray-800", children: ({ open }) => (_jsxs(_Fragment, { children: [_jsx("div", { className: "mx-auto max-w-7xl px-2 sm:px-6 lg:px-8", children: _jsxs("div", { className: "relative flex h-16 items-center justify-between", children: [_jsx("div", { className: "absolute inset-y-0 left-0 flex items-center sm:hidden", children: _jsxs(Disclosure.Button, { className: "relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white", children: [_jsx("span", { className: "absolute -inset-0.5" }), _jsx("span", { className: "sr-only", children: "Open main menu" }), open ? (_jsx(XMarkIcon, { className: "block h-6 w-6", "aria-hidden": "true" })) : (_jsx(Bars3Icon, { className: "block h-6 w-6", "aria-hidden": "true" }))] }) }), _jsxs("div", { className: "flex flex-1 items-center justify-center sm:items-stretch sm:justify-start", children: [_jsx("div", { className: "flex flex-shrink-0 items-center", children: _jsx(Link, { to: "/", children: _jsx("h1", { className: "text-3xl font-bold text-purple ml-5", children: "Rekoda" }) }) }), _jsx("div", { className: "hidden sm:ml-6 sm:block", children: _jsx("div", { className: "flex space-x-4", children: navigation.map((item) => (_jsx("a", { href: item.href, className: classNames(item.current
                                                    ? "bg-gray-900 text-white"
                                                    : "text-gray-300 hover:bg-gray-700 hover:text-white", "rounded-md px-3 py-2 text-sm font-medium"), "aria-current": item.current ? "page" : undefined, children: item.name }, item.name))) }) })] }), _jsxs("div", { className: "absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0", children: [_jsxs("button", { type: "button", className: "relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800", children: [_jsx("span", { className: "absolute -inset-1.5" }), _jsx("span", { className: "sr-only", children: "View notifications" }), _jsx(BellIcon, { className: "h-6 w-6", "aria-hidden": "true" })] }), _jsxs(Menu, { as: "div", className: "relative ml-3", children: [_jsx("div", { children: _jsxs(Menu.Button, { className: "relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800", children: [_jsx("span", { className: "absolute -inset-1.5" }), _jsx("span", { className: "sr-only", children: "Open user menu" }), _jsx("img", { className: "h-8 w-8 rounded-full", src: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80", alt: "" })] }) }), _jsx(Transition, { as: Fragment, enter: "transition ease-out duration-100", enterFrom: "transform opacity-0 scale-95", enterTo: "transform opacity-100 scale-100", leave: "transition ease-in duration-75", leaveFrom: "transform opacity-100 scale-100", leaveTo: "transform opacity-0 scale-95", children: _jsxs(Menu.Items, { className: "absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none", children: [_jsx(Menu.Item, { children: ({ active }) => (_jsx("a", { href: "#", className: classNames(active ? "bg-gray-100" : "", "block px-4 py-2 text-sm text-gray-700"), children: "Your Profile" })) }), _jsx(Menu.Item, { children: ({ active }) => (_jsx("div", { className: "text-center", children: userInfo ? (_jsx("button", { onClick: () => dispatch(logoutUser()), className: classNames(active ? "bg-gray-100" : "", "block px-4 py-2 text-sm text-gray-700"), children: "Logout" })) : (_jsx(NavLink, { className: "button", to: "/login", children: _jsx("button", { className: classNames(active ? "bg-gray-100 text-blue" : "", "block px-4 py-2 text-sm text-gray-700"), children: "Login" }) })) })) })] }) })] })] })] }) }), _jsx(Disclosure.Panel, { className: "sm:hidden", children: _jsx("div", { className: "space-y-1 px-2 pb-3 pt-2", children: navigation.map((item) => (_jsx(Disclosure.Button, { as: "a", href: item.href, className: classNames(item.current
                                ? "bg-gray-900 text-white"
                                : "text-gray-300 hover:bg-gray-700 hover:text-white", "block rounded-md px-3 py-2 text-base font-medium"), "aria-current": item.current ? "page" : undefined, children: item.name }, item.name))) }) })] })) }));
}
